### PR TITLE
Restructure build/packaging to newest Mumble specs

### LINKED ISSUE #123: Update to current Mumble API / updater bundles
- [x] C Header changes, see: https://github.com/mumble-voip/mumble/pull/5095#issuecomment-853915534
- [x] Bundling also changes: https://github.com/mumble-voip/mumble/pull/5102
  - docs at https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/Bundling.md; recent proposal: https://github.com/Krzmbrzl/mumble/blob/plugin-installer-manifest/docs/dev/plugins/Bundling.md
  - <s>ongoing</s> discussion about binary package format / zip support: https://github.com/mumble-voip/mumble
  - [x] updater needs to be pointed at the `.mumble_plugin` binary distribution/discussions/5107
- [x] Implement Manifest file specs (generate in makefile, details: https://github.com/mumble-voip/mumble/pull/5117)
- [x] thereby restructure build process to have the plugin makefile just build the plugin, and have the overall makefile deal with packaging

### PR DESCRIPTION
**Pull request by hbeni**
Implement latest packaging specs for Mumble (https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/Bundling.md)

(Fix #123)

### CODE REVIEW

**Comment by hbeni** [comment]
@krzmbrzl, @fdalvi  gets an error when trying to install on MacOS:
grafik

Is there an error distinguishing between the linux `.so` and macos `.bundle` again?

**Comment by hbeni** [comment]
Fahims mumble build was: https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=4864&view=results
Tested plugin: https://github.com/hbeni/fgcom-mumble/suites/2934902870/artifacts/65926410

**Comment by hbeni** [comment]
@fdalvi
Does this file work with the aforementioned mumble snapshot?
-> [fgcom-mumble_macos_x86_64.bundle.zip](https://github.com/hbeni/fgcom-mumble/files/6638109/fgcom-mumble_macos_x86_64.bundle.zip)
(if it doesn't, please unzip it manually)

**Comment by Krzmbrzl** [comment]
This should be the same error as before. As of now Mumble only checks whether a shared library is loadable which is true for both types of libraries on macOS.

This will only be fixed with the introduction of the manifest file.
Until then you'll have to extract the zip and install the .bundle separately.

**Comment by hbeni** [comment]
Ah of course. I somehow was of the impression the rename to `.bundle` already fixed it.

@fdalvi if the single file above works, then all is ok for now.
Robert is already working on the enhanced updater meanwhile, and when that is ready i can push the latest bits to this branch/pr here to make the plugin updater conforming again.

**Comment by fdalvi** [comment]
@hbeni Unfortunately the single file does not work either. I get the following error:

Screen Shot 2021-06-11 at 4 58 58 PM

Trying to move (the extracted file i.e. *.bundle) to the Plugins directory manually and then starting Mumble prints this in the sidebar:

`Non-plugin found in plugin directory: "/<mumble-dir>/Mumble/Plugins/fgcom-mumble_macos_x86_64.bundle"`

**Comment by Krzmbrzl** [comment]
Now that is interesting :eyes: 
This can mean one of two things:
1. Mumble was unable to load the shared library at all
2. Mumble was able to load the lib but it can't find all required functions in it

I will simply assume that the functions have not been tempered with in the fgcom plugin and therefore (given that it used to load fine) I assume that for some reason the library is not loadable.
Was anything changed in terms of how this lib is built? Was it perhaps corrupted during download / extraction?

**Comment by hbeni** [comment]
> I will simply assume that the functions have not been tempered with in the fgcom plugin and therefore (given that it used to load fine) I assume that for some reason the library is not loadable.

Not that I'm aware of. In fact, in Linux currently it still works.
Fahim confirmed that it once worked on the [previous 0.13.0 release](https://github.com/hbeni/fgcom-mumble/releases/tag/v.0.13.0).

The two commits that may be suspicious are 7f6f8027 and 33141e383a.

I currently rebuild the plugin and mumble from scratch here, maybe i just don't see the error because of old files?

**Comment by hbeni** [comment]
> I currently rebuild the plugin and mumble from scratch here

Done, all is fine here, plugin loads.

I looked at the build process too, but changes mainly involve renamig of the [produced binaries](https://github.com/hbeni/fgcom-mumble/pull/124/files#diff-a3468ff14af97bb1e813ead6701e9b223b8dd3e871e6ade451761bc21773eccb).

**Comment by hbeni** [comment]
I just noticed that i did not change the signature of `mumble_init(uint32_t id)` to `mumble_init(mumble_plugin_id_t id)`:
https://github.com/hbeni/fgcom-mumble/commit/33141e383a08362c5377c1360de11b9471685b19#diff-0b16379986e04d2487febc06c15906ab6673bd8311bdccf740baeebcf5f74942

But i suspect this should not trigger this? (nonetheless i changed this).

Or maybe is the C-Header change not yet contained in your mumble branch?

**Comment by Krzmbrzl** [comment]
> But i suspect this should not trigger this? (nonetheless i changed this).

It should not as `mumble_plugin_id_t` is typedef'd to `uint32_t`. Therefore as of now these are exactly the same.

> Or maybe is the C-Header change not yet contained in your mumble branch?

That should also be no issue since the latest header changes don't change any underlying types, only the names of them. The final program however does not even know about the variable names and therefore there should be absolutely no difference.

@fdalvi are you building Mumble yourself? If you you could pass the `-Dplugin-debug=ON` option to cmake. This will then dump some info to the logs that should clearly tell us what is going on...

**Comment by fdalvi** [comment]
@Krzmbrzl I was able to successfully build Mumble from the master branch, but unfortunately no relevant output in the log when running Mumble from the command line:

```
./Mumble
<D>2021-06-12 15:28:31.931 libopus 1.3.1 from libopus.dylib
<W>2021-06-12 15:28:31.972 Theme: "Mumble"
<W>2021-06-12 15:28:31.972 Style: "Lite"
<W>2021-06-12 15:28:31.972 --> qss: ":themes/Default/OSX Lite.qss"
<W>2021-06-12 15:28:31.972 Using Mac OS X system language as locale name
<W>2021-06-12 15:28:31.972 Locale is "en_US" (System: "en_US")
<W>2021-06-12 15:28:32.333 Populating font family aliases took 310 ms. Replace uses of missing font family "-apple-system" with one that exists to avoid this cost.
<W>2021-06-12 15:28:32.478 Database SQLite: "3.33.0"
<D>2021-06-12 15:28:32.503 Found built-in plugin 'Manual placement' at "<builtin>"
<D>2021-06-12 15:28:32.503 Its description: This is the manual placement plugin. It allows you to place yourself manually.
<W>2021-06-12 15:28:32.736 Updating application palette
<W>2021-06-12 15:28:32.823 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<D>2021-06-12 15:28:33.280 CoreAudioInput: Checking microphone permission....
<D>2021-06-12 15:28:33.424 CoreAudioInput: Checking microphone permission passed.
<W>2021-06-12 15:28:33.424 AudioInput: Opus encoder set for high quality speech
<W>2021-06-12 15:28:33.424 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2021-06-12 15:28:33.424 CoreAudioInput: Set device to 'Default Device'.
<W>2021-06-12 15:28:33.426 CoreAudioOutput: Set device to 'AppleHDAEngineOutput:1F,3,0,1,2:0'.
<D>2021-06-12 15:28:33.504 CoreAudioInput: Use AUHAL as IO AudioUnit.
<W>2021-06-12 15:28:33.524 CoreAudioInput: Input device with more than one channel detected. Defaulting to 1.
<W>2021-06-12 15:28:33.524 AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
<W>2021-06-12 15:28:33.524 CoreAudioInput: BufferFrameSizeRange = (14.00, 4096.00)
<W>2021-06-12 15:28:33.525 AudioOutput: Initialized 2 channel 44100 hz mixer
<W>2021-06-12 15:28:33.525 CoreAudioOutput: BufferFrameSizeRange = (14.00, 4096.00)
<W>2021-06-12 15:28:33.600 AudioInput: Using RNNoise as noise canceller
warning: The VAD has been replaced by a hack pending a complete rewrite
<D>2021-06-12 15:28:36.470 CoreAudioInput: Checking microphone permission....
<D>2021-06-12 15:28:36.485 CoreAudioInput: Checking microphone permission passed.
<D>2021-06-12 15:28:36.524 CoreAudioInput: Checking microphone permission....
<D>2021-06-12 15:28:36.538 CoreAudioInput: Checking microphone permission passed.
<D>2021-06-12 15:28:36.538 CoreAudioInput: Checking microphone permission....
<D>2021-06-12 15:28:36.553 CoreAudioInput: Checking microphone permission passed.
<W>2021-06-12 15:30:56.589 Session likely ending. Suppressing ask on quit
<W>2021-06-12 15:30:56.660 CoreAudioInput: Shutting down.
<W>2021-06-12 15:30:56.686 CoreAudioOutput: Shutting down.
```

This run was starting mumble, trying to install plugin (unsuccessfully) and then quitting mumble.

I did build with the cmake flag `-Dplugin-debug=ON`, but maybe I need to enable more verbose logging?

**Comment by Krzmbrzl** [comment]
@fdalvi do you have any other plugins installed? If yes then the compile option did not work. If no this means that the library is indeed not loadable.

**Comment by fdalvi** [comment]
I see the default ‘manual placement’ plugin in the list, but nothing else -
should I try and install some other plugin?

**Comment by hbeni** [comment]
What also may be interesting:
Robert, you said that the api should be compatible to older plugins. However, Fahim tried to load the 0.14.0 plugin which previously worked.

Fahim, can you retry to unzip the .bundle plugin from the last two released and try to load it?

**Comment by Krzmbrzl** [comment]
> I see the default ‘manual placement’ plugin in the list, but nothing else -
should I try and install some other plugin?

Ah okay then you do indeed not have any other plugin installed. Then it seems that the most likely cause for the issue is that the macOS binary is not loadable. 

Following https://stackoverflow.com/questions/4506121/how-to-print-a-list-of-symbols-exported-from-a-dynamic-library you could try to print the list of exported symbols of the lib. Maybe this will shed some light on the issue :eyes: 

> Robert, you said that the api should be compatible to older plugins. However, Fahim tried to load the 0.14.0 plugin which previously worked.

Yes it _should_ work :see_no_evil:

**Comment by Krzmbrzl** [comment]
@fdalvi if you are to build a debug build of Mumble, you should have the testPlugin listed as an installed plugin. For this you should then see some output of the `-Dplugin-debug` option in the console. That way we could be sure that the plugin framework is behaving as intended and it is indeed the macOS plugin binary that is causing issues :eyes:

**Comment by fdalvi** [comment]
@Krzmbrzl I tried doing a clean build of the `master` branch with the following cmake config:

```bash
cmake -Dserver=OFF -Dplugin-debug=ON ..
```

However, I do not see any "testPlugin" in the plugin list; Only the manual placement one, so maybe I'm not building mumble correctly?

I also tried to export the symbols as you asked, but I am not well versed enough to know if there is something wrong with it. I've attached it here nevertheless.
[fgcom-mumble-macOS.bundle.exportedsymbols.txt](https://github.com/hbeni/fgcom-mumble/files/6657790/fgcom-mumble-macOS.bundle.exportedsymbols.txt)

**Comment by Krzmbrzl** [comment]
Yeah as I said you'll have to create a _Debug_ build. So like this:
```
cmake -DCMAKE_BUILD_TYPE=Debug -Dserver=OFF ..
```

**Comment by hbeni** [comment]
I opened a new ticket to have it concise: #126

**Pull request merged**
