### PR TITLE
EXPERIMENT: fix locking issues

### LINKED ISSUE #76: Bug: Freeze of mumble GUI
**Describe the bug**
The mumble GUI freezes
- when changing channels
- when joining the server

(Maybe related to #65)

**To Reproduce**
a) Join the server
b) change channels
The bug does not reliably trigger, but @mill-j seem to be able to reproduce it reliably

**Expected behavior**
No freeze of the GUI

**Additional context**
- Maybe related to #65

### PR DESCRIPTION
**Pull request by hbeni**
fix #76 

:warning: The branch probably is just an experiment, not intended for merging.

### CODE REVIEW

**Comment by hbeni** [comment]
@mill-j Can you test this please?

**Comment by mill-j** [comment]
Had to add #define gettid() syscall(SYS_gettid) to io_plugin.cpp to get this to compile. It appears to properly unlock every time. but the mumble gui still hangs. 

FGCom [2021-02-12 08:47:46.595 @tid=9258]: [DBG] fgcom_remotecfg_mtx.lock()
FGCom [2021-02-12 08:47:46.595 @tid=9258]: [DBG] fgcom_remotecfg_mtx.unlock()

**Comment by hbeni** [comment]
cool thanks for responding so quickly.
Can you attach the entire terminal log here, preferrably as text file?

**Comment by hbeni** [comment]
Oh, and.... what compiler do you use?
(i have `gcc version 10.2.1 20210110 (Debian 10.2.1-6)`)

**Comment by mill-j** [comment]
[freezelog.txt](https://github.com/hbeni/fgcom-mumble/files/5972584/freezelog.txt)
Using gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Looks like gettid() is an older glib problem, I found this:
[code]
#if __GLIBC__ == 2 && __GLIBC_MINOR__ < 30
#include <sys/syscall.h>
#define gettid() syscall(SYS_gettid)
#endif 
[/code]

**Comment by hbeni** [comment]
You don't have the chance to upgrade your gcc and the libs, don't you?
Maybe you just have some gcc issue here - i know there were significant changes to pthreads a while ago...

**Comment by mill-j** [comment]
I could but my distro is not rolling and i'd like to get a little more use out of this install before reinstalling. The gettid() not being found is a glib bug not gcc.

**Comment by hbeni** [comment]
Ok, what i have found. Two threads try to lock the `fgcom_localcfg_mtx`.

Line 4509: `FGCom [2021-02-12 09:02:29.048 @tid=9503]: [DBG] fgcom_localcfg_mtx.lock()`
Line 4555: `FGCom [2021-02-12 09:02:29.091 @tid=9489]: [DBG] fgcom_localcfg_mtx.lock()`

thread 9503 was the UDP-Server thread.
thread 9489 was mumble's main thread.

So first the UDP server locks (successfully) and then the lock cannot be aquired by mumbles main thread, causing it to freeze.
The place where this happens after is somewhere blow the log messages in `fgcom_mumble.cpp`, Lines 487. That's in the online init part.

The last thing, the UDP server did was:
`FGCom [2021-02-12 09:02:29.077 @tid=9503]: [DBG] [UDP-server] Parsing token: COM2_PTT=0`
So probably the main question is, what happens here that stops the UDP server...?

**Comment by hbeni** [comment]
The PTT field will cause `fgcom_handlePTT` to be invoked, which in turn calls `mumAPI.requestMicrophoneActivationOvewrite(ownPluginID, false);` at the end.

That _may_ be our cause (because the main thread is blocked currently).
I just moved the debug message (we didn't probably see because of the stalling call) above that line.

:point_up: If we can see that message in the log now, that would proof the case.
What do you get now?

**Comment by mill-j** [comment]
[freezelog3.txt](https://github.com/hbeni/fgcom-mumble/files/5972803/freezelog3.txt)

**Comment by hbeni** [comment]
@Krzmbrzl I think we got a trace now regarding [my problem](https://github.com/mumble-voip/mumble/pull/3743#issuecomment-778242820] in https://github.com/mumble-voip/mumble/pull/3743.
It seems that `mumAPI.requestMicrophoneActivationOvewrite` is related to the issue.
What i don't understand yet is why that causes the main mumble thread to kick in - shouldn't the API request just be performed and return immediately?
And what plugin callback is called from that action?


----

**Details:**
That really sounds like we found it, and is most probably what [Robert describes also](https://github.com/mumble-voip/mumble/pull/3743#issuecomment-778264199): 
```
FGCom [2021-02-12 09:40:07.579 @tid=10308]: [DBG] fgcom_localcfg_mtx.lock()
FGCom [2021-02-12 09:40:07.579 @tid=10308]: [DBG] [UDP-server] Segment='CALLSIGN=Test'
FGCom [2021-02-12 09:40:07.579 @tid=10308]: [DBG] [UDP-server] Parsing token: CALLSIGN=Test
FGCom [2021-02-12 09:40:07.579 @tid=10308]: [DBG] [UDP-server] identity portmap result: clientHostPort(127.0.0.1:45027) => iid(0)
FGCom [2021-02-12 09:40:07.579 @tid=10308]: [DBG] [UDP-server] Segment='LAT=48.3440238'
FGCom [2021-02-12 09:40:07.579 @tid=10308]: [DBG] [UDP-server] Parsing token: LAT=48.3440238
FGCom [2021-02-12 09:40:07.580 @tid=10308]: [DBG] [UDP-server] Segment='LON=11.765083'
FGCom [2021-02-12 09:40:07.580 @tid=10308]: [DBG] [UDP-server] Parsing token: LON=11.765083
FGCom [2021-02-12 09:40:07.580 @tid=10308]: [DBG] [UDP-server] Segment='HGT=6.6'
FGCom [2021-02-12 09:40:07.580 @tid=10308]: [DBG] [UDP-server] Parsing token: HGT=6.6
FGCom [2021-02-12 09:40:07.580 @tid=10308]: [DBG] [UDP-server] Segment='COM1_PTT=0'
FGCom [2021-02-12 09:40:07.580 @tid=10308]: [DBG] [UDP-server] Parsing token: COM1_PTT=0
FGCom [2021-02-12 09:40:07.581 @tid=10308]: [DBG] Handling PTT state: PLUGIN NOT ACTIVE
FGCom [2021-02-12 09:40:07.643 @tid=10297]: [DBG] fgcom_localcfg_mtx.lock()
FGCom [2021-02-12 09:40:08.186 @tid=10309]: [DBG] fgcom_localcfg_mtx.lock()
```
- 10308 is the UPD sever locking the local state, processing the `COM1_PTT=0` UDP field, which causes it to invoke `fgcom_handlePTT` which calls the API `mumAPI.requestMicrophoneActivationOvewrite`
- 10297 is mumbles main thread, trying to get a lock *somewhere* in the plugin code, and waits until the lock gets released.
- 10309 is the GC thread in this case (which is probably unrelated as he can wait without harm)

**Comment by hbeni** [comment]
@mill-j 9148346 tries to move the problematic call in the UDP thread out of the critical path.
The PTT handling is now at it's end, and thus the mumble API call is not inside the locks anymore.

**Comment by Krzmbrzl** [comment]
> What i don't understand yet is why that causes the main mumble thread to kick in - shouldn't the API request just be performed and return immediately?

Each and every API call is now blocking. The reason for that is that for a non-blocking version we can't provide the caller with a proper exit code. And even the mentioned function checks the plugin ID. So if we were to perform the actual call asynchronously the caller would not notice (by the exit code) that the provided plugin ID is invalid.

I am planning on introducing a special option to execute such methods in a non-blocking way. This way the caller could say "I don't care about the exit code" and then that'd work. But this has to be opt-in for the reason mentioned above.

But for the time being all API functions must be considered as potentially blocking.

**Comment by hbeni** [comment]
Thanks for elaborating!

**Comment by mill-j** [comment]
Hey that last [commit](https://github.com/hbeni/fgcom-mumble/commit/91483465906c46bed2e53fb176fc5ba4498b8e37) seemed to fix the freezing! I can connect RadioGUI, start mumble, connect to the server and connect to the channel, without having the mumble gui freeze.

**Comment by hbeni** [comment]
What about the stuttering?
It may be related

**Comment by Krzmbrzl** [comment]
Perfect! So then the cause has been identified :party:

**Comment by mill-j** [comment]
The stuttering is still there. So it's a seperate issue.

**Comment by hbeni** [comment]
Ok cool!

So I think I will pick the relevant changes to master and we close this.

**Comment by hbeni** [comment]
Well, if you change back the mutex definition to normal mutex, does it still work?

**Comment by mill-j** [comment]
It still works the same with that reverted. It's probably just be coincidece but it seems to stutter less after reverting.

**Comment by hbeni** [comment]
Pushed to master: c5ba8e8..88e74b8
(you may retry with master, to get sure, but i'm pretty confident)

**Comment by mill-j** [comment]
Confirmed that it still works as intended in the latest master commit.

**Pull request closed without merging**
