### PR TITLE
FGFS Addon: Intercom support

### PR DESCRIPTION
**Pull request by hbeni**
Adds intercom support for use in FGFS copilot mode.

Intercom functionality is automatically enabled when you make a connection using the FGFS copilot module.

### CODE REVIEW

**Comment by hbeni** [comment]
I have a first draft local here, still needs some tuning.

Three things are issues right now:

1. The Combar code is rather fixed and i have no good idea yet how i can dynamically create the additional buttons. I would like to show the IC button only when there is actually IC functionality, as most of the time there will be no IC.
2. The code to detect an established copilot connection is yet to be done. This is not as easy as it looks, because of lacking properties. Still searching.
3. There seems to be a size limit for a `getValue()` call. Currently, COM4's UDP code will be truncated, despite beeing there in the property. I think I remember that i already encountered that problem while testing a prior version of the FGFS addon, but I'm not sure what the clue was - I think it was some limit in C code. Maybe we need to add some kind of multiplexer or so, to write COM1-3 to one out property, COM4-6 to another, both transmitted in the protocol file.

**Comment by hbeni** [comment]
Investigated 3. a little further. Its not the property, and from nasal space it is readable in its entirity.
It looks like something in the protocol.xml/io module that truncates this to 368 chars.

**Comment by hbeni** [comment]
Connecting to Intercom based on dual control module now also works.

Test with two instances:
```
#--multiplay=in,10,127.0.0.1,5010 --multiplay=out,10,127.0.0.1,5011 --callsign=T-EST1
#--multiplay=in,10,127.0.0.1,5011 --multiplay=out,10,127.0.0.1,5010 --callsign=T-EST2
```

or set `--prop:/sim/remote/pilot-callsign=T-EST1` manually

**Comment by hbeni** [comment]
@MariuszXC Hi Mariusz, I think this is ready for testing :) :tada:

**Comment by MariuszXC** [comment]
@hbeni I'll give it a fg once real life settles up a bit, i.e. about a week from now (hopefully) ;)

**Comment by hbeni** [comment]
Or we use GA-Wendesday tomorrow, if I can join (which looks good at the moment) for a short test

**Comment by hbeni** [comment]
Just did a quick test (two FGFS instances, two mumble instances), and it worked trough normal multiplayer via mp01

**Comment by hbeni** [comment]
Hm, maybe we should switch the callsign mapping to another separator (hash? pipe? underscore?), so it would be easier to process via scripts or so in the future.
What do you think?

**Pull request merged**
