### PR TITLE
Initial fgcom_stateManger implemetation.

### PR DESCRIPTION
**Pull request by mill-j**
@hbeni Something like this?

This basically adds another layer to manage fgcom_identity instances outside of the main plugin class. I should allow us to implement more user management functions witthout cluttering up the main plugin class.

 No other functionallity in the plugin has been added although several functions recieved better documentation.

### CODE REVIEW

**Comment by hbeni** [comment]
Sounds basicly good.
Two things come to my mind, however:
1. Is the clearing/manipulating of the remote identities thread safe? i think we would want a mutex/lock_guard for this...
2. The Local identities must be a hashmap. The reason is, the local instance may manage more than one identity; for example if you connect two different ATC instances to the same mumble plugin instance (to simulate several different locations managed by the same ATC).

I thought that i wrote that into the specification already, have to recheck if i missed that....

**Comment by mill-j** [comment]
I'm not sure about thread safe. I'll check into that.

The multiple local instances does have me confused. I knew the docs said that the current plugin supports it but how do you tell which data comes from where? Assuming both come in on the same port.

**Comment by hbeni** [comment]
> which data comes from where? Assuming both come in on the same port.
> Edit: I think I understand it now. I missed "Client Port".

Exaclty. And then there is the `IID` protocol field which can override it too (however it's not used from anywhere now, but for debugging purposes this was already useful)

**Comment by mill-j** [comment]
Ok I think I'm getting a better grasp of what needs to happen, correct me if I'm wrong. For every local and remote **state** (aka mumble user), there needs to be the ability to have a dynamic number of identities. So that means adding a fgcom_state class beween fgcom_stateManager and fgcom_identity will likely be needed.

**Comment by hbeni** [comment]
Hm, I think that the State manager already can do this. The identity is the main state class, and the state manager just need to be able to hold different identities per:
a) local client
b) remote client

**Comment by mill-j** [comment]
```
Hm, I think that the State manager already can do this. The identity is the main state class, and the state manager just need to be able to hold different identities per:
a) local client
b) remote client
```
True, it is possible to add a IID field to the fgcom_identity and turn local user into an array. This might be just as easy and clean as adding a state class. I'll see what I can do.

**Comment by hbeni** [comment]
I think that the identity does not even need the id field, just the client port number which will also be needed by the rdf udp client.

**Pull request merged**
