### PR TITLE
Add time selection option to statuspage/usage

### PR DESCRIPTION
**Pull request by hbeni**
This adds the option to select timeframes for the statuspage usage link as GET parameters.
Default is one week into the past from now.

Using gnuplot for the selection allws us to keep the usage data for longer timeframes and conserves performance in the statusbot, because it still just needs to append new data.

```
- last:      ammount of hours to display from now into the past
- from:      fixing the selected timeframe start to this timestamp ('last' will be ignored obviously)
- to:        fixing the selected timeframe end to this timestamp

Examples:
?usage                             displays the rolling last week
?usage&last=24                     displays the rolling last day
?usage&from=20210101&to=20210131   displays Jan 2021
```
----
Implements #95

### CODE REVIEW

**Comment by hbeni** [comment]
@mill-j Just upgraded the experimental server to this PR:
- http://fgcom.hallinger.org/?usage
- http://fgcom.hallinger.org/?usage&last=48
- http://fgcom.hallinger.org/?usage&from=20210316
- http://fgcom.hallinger.org/?usage&from=202103171800&to=202103171900

What do you think of this?

**Comment by mill-j** [comment]
Very good! This gives you a much better idea how much it has been used recently. One more question though: are you planning to add several quick links to the home page? Not sure what would look/fit best.

**Comment by hbeni** [comment]
> One more question though: are you planning to add several quick links to the home page?

Yes, I had tought about it, but dismissed the idea: my conclusion was that the usage stats for one week would probably give most people a good impression of the usage. Also I think, that i probably will be the main user of that stats, or do ordinary people actually care about such information?

A middle ground may be to add a web layer on the linked page that does not directly generate the picture but shows some control elements and embed the resulting image.
But is it worth the effort?

**Comment by mill-j** [comment]
```
But is it worth the effort?
```
Very likely not. It is unneeded, most end users couldn't care less. As long as the documentation for the server admin mentions it, that should be great.

**Comment by hbeni** [comment]
> As long as the documentation for the server admin mentions it, that should be great.

Is this good enough already, or do you miss something:
https://github.com/hbeni/fgcom-mumble/blob/Issue-95/server/statuspage/Readme.statuspage.md#usage-statistics

**Comment by mill-j** [comment]
Oh sorry, I missed that when I glanced through the commits. Looks great.

**Comment by hbeni** [comment]
Cool, then i merge it :)

**Pull request merged**
