### PR TITLE
FlightGear Addon

### LINKED ISSUE #88: FGFS Addon integration
To make things easier for fgfs users, it would be cool to have a simple addon that just needs to be put into the launcher.

- [x] make addon structure: https://wiki.flightgear.org/Addon
- [x] Integrate protocol file
- [x] add Menu option in multiplayer menu to setup and activate the protocol
- [x] Documentation/install instructions in readme

- - -

I got some hints at the mailing list:
> See:
> - https://github.com/slawekmikula/flightgear-addon-littlenavmap
> - https://github.com/slawekmikula/flightgear-addon-vfrflight
> - https://github.com/slawekmikula/flightgear-addon-protocolkml
> - https://github.com/slawekmikula/flightgear-addon-linuxtrack

### PR DESCRIPTION
**Pull request by hbeni**
Resolve #88

### CODE REVIEW

**Comment by mill-j** [comment]
I did a quick test, it worked as intended. It will certainly be much easier for users. Looking at the code, it doesn't look like it will be hard to maintain either. Good job.

**Comment by hbeni** [comment]
Thx for the test!

before i merge this, i want to see if i can iron out the last two „issues“, but they are not blockers:
- it would be cool if the settings could be persistent, so that if users setup other ports/hosts, they do not need to do it everytime
- It would be nice to have the config options in the core-multiplayer menu instead of a custom one

**Comment by mill-j** [comment]
```
it would be cool if the settings could be persistent, so that if users setup other ports/hosts, they do not need to do it everytime
It would be nice to have the config options in the core-multiplayer menu instead of a custom one
```
That would be great. If it is not possible to add fgcom-mumble to the multiplayer menu, I'd suggest renaming the new menu item fgcom-mumble instead of Add-On.

**Comment by hbeni** [comment]
> I'd suggest renaming the new menu item fgcom-mumble instead of Add-On.

I was off the impression that the add-on menu item is a generic one all add-one should add their items to?

**Comment by mill-j** [comment]
```
I was off the impression that the add-on menu item is a generic one all add-one should add their items to?
```
I don't know, I didn't dig that deep yet. It's very likely. In that case that is where people should expect to find it.

**Comment by hbeni** [comment]
Both solved now :)

**Comment by hbeni** [comment]
I will merge soon and then adjust the wiki entry.

**Pull request merged**
